#include "settings.h"

int N_POLY_POINTS = 3;
int N_COLOR_VAR = 10;
int N_POS_VAR = 0;
int GUI_REFRESH_RATE = 1;
int AUTOFOCUS_RES = 2;
int N_CORES = 4;

int FOCUS_LEFT=0, FOCUS_RIGHT=100, FOCUS_TOP=0, FOCUS_BOTTOM=100;

int POLYS_MIN=15, POLYS_MAX=50;

// Rates of mutation in 1/X odds of happening per generation
int POLYS_ADD_RATE=1;
int POLYS_REMOVE_RATE=1500;
int POLYS_REORDER_RATE=700;
int POINT_ADD_RATE=1500;
int POINT_DELETE_RATE=1500;
int POINT_MOVE_MAX_RATE=100;
int POINT_MOVE_MED_RATE=50;
int POINT_MOVE_MIN_RATE=50;
int RED_CHANGE_RATE=100;
int GREEN_CHANGE_RATE=100;
int BLUE_CHANGE_RATE=100;
int ALPHA_CHANGE_RATE=200;

// Ranges
int POINT_MOVE_MED_RANGE=40;
int POINT_MOVE_MIN_RANGE=6;
int ALPHA_MIN=30;
int ALPHA_MAX=180;

