#include "stats.h"

unsigned STAT_POLY_ADD=0, STAT_POLY_REMOVE=0, STAT_POLY_REORDER=0;
unsigned STAT_POINT_MOVE_MAX=0, STAT_POINT_MOVE_MED=0, STAT_POINT_MOVE_MIN=0;

unsigned STAT_POLY_ADD_OK=0, STAT_POLY_REMOVE_OK=0, STAT_POLY_REORDER_OK=0;
unsigned STAT_POINT_MOVE_MAX_OK=0, STAT_POINT_MOVE_MED_OK=0, STAT_POINT_MOVE_MIN_OK=0;
